### ISSUE TITLE
The library doesn't work at all

### ISSUE THREAD

**Issue by nocturn9x** [MushroomMaula/fastapi_login#17]
I tried multiple times using this library, but it doesn't seem to work. When I generate the access token, I also do `response.set_cookie` to save it for the current session. The library correctly retrieves the cookie at the next request, but (I tested it) `fastapi.security.utils.get_authorization_scheme_param` returns `''` as the second parameter of its tuple, which I guess means the provided jwt is invalid, but the access token comes directly from `create_access_token`! Also, the `__call__` method checks `if token is not None`, but it should actually be `if not token`, because otherwise weird stuff happens (the custom not authenticated exception is ignored). That's because token equals an empty string, not `None`

**Comment by MushroomMaula** [comment]
What does the cookie in your case look like? If you look at the [source code of fastapi.security.utils.get_authorization_scheme_param](https://github.com/tiangolo/fastapi/blob/master/fastapi/security/utils.py) it just splits the cookie at the first space. Therefore if your cookie looks for example like this:
```py
cookie = "Bearer "
```
Then `cookie.partition(" ")` will return `('Bearer', ' ', '')`
Regarding the if statement you are correct however the bug lies inside the `_token_from_cookie` method as it should not return an empty string but rather None

**Comment by nocturn9x** [comment]
Oh, I see, I used to save the cookie without the `"Bearer" prefix, should I do something like this then? `response.set_cookie(key="login", value=f"Bearer {access_token}")`?

**Comment by MushroomMaula** [comment]
Actually I never thought about storing the cookie without the `Bearer ` prefix as one does when using the authorization header. I will look into best practices regarding storing the token inside the cookie and report back.
If you need to get it working before the next update add the `Bearer ` prefix

**Comment by MushroomMaula** [comment]
I just published version 1.5.1 which now supports cookies without the `Bearer ` prefix
